implement WordPress coding standards (#7)
WarenGonzaga/shortcodes-wp pull request #11
Opened 2021-10-18 07:59 UTC by ChristofLee

This is an example of we can use PHPCS and PHPCBF to format our code and standardise it.

Solves #7.

2021-10-23 13:04 UTC, warengonzaga commented
@ChristofLee don't forget to update this.

2021-10-23 14:10 UTC, ChristofLee commented
Was awaiting your approval on this code style. I'll take this as your happy with it and I will update this PR asap.

2021-10-23 14:12 UTC, warengonzaga commented
> Was awaiting your approval on this code style. I'll take this as your happy with it and I will update this PR asap.

your PR is currently in draft... ask me for a review if you are ready.

2021-10-24 04:17 UTC, warengonzaga requested changes
Overall good for me however please revert back the lowercase for single line comments.

2021-10-24 04:17 UTC, warengonzaga commented on shortcodes-wp.php
> +// Prevent direct access.
Keep this single comments in lowercase.

2021-10-24 04:17 UTC, warengonzaga commented on shortcodes-wp.php
> +	// Display output.
Same here, keep this in lowercase for single comments.

2021-10-24 04:17 UTC, warengonzaga commented on shortcodes-wp.php
> -    // display output
Another one!

2021-10-24 19:31 UTC, closed without merging

2021-10-24 19:31 UTC, ChristofLee commented
Contains fixes from other branches and is not isolated to this one issue. I will start again and make a new PR.